=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3school.com.cn"
xmlns="http://www.w3school.com.cn"
elementFormDefault="qualified">
  <xs:element name="meeting">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="place" type="xs:string"/>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="partner" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex10a.xml
<?xml version="1.0" encoding="UTF-8"?>
<meeting xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex10.xsd">
  <place>Leipzig</place><date>2007-12-03</date>
    <partner>Vorstand</partner>
  <place>Dresden</place><date>2007-08-02</date>
    <partner>representative</partner>  
  <place>Erfurt</place><date>2007-09-01</date>
    <partner>Chef</partner>
  <place>Hamburg</place><date>2007-03-08</date>
    <partner>Student</partner>
</meeting>
