=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex15.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3school.com.cn"
xmlns="http://www.w3school.com.cn"
elementFormDefault="qualified">
  <xs:element name="staffFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="person" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="firstName" type="xs:string"/>
              <xs:element name="familyName" type="xs:string"/>
              <xs:element name="psnr">
                <xs:simpleType>
                  <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="100"/>
                    <xs:maxInclusive value="10000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element ref="grade" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="grade">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger">
        <xs:pattern value="[1-5]{1}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex15b.xml
<?xml version="1.0" encoding="UTF-8"?>
<staffFile xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex15.xsd">
  <person>
    <firstName>Martin</firstName>
    <familyName>Immhofer</familyName>
    <gender>male</gender>
    <psnr>2463</psnr>
  </person>
  <person>
    <firstName>Herbert</firstName>
    <familyName>Leisnig</familyName>
    <psnr>5678</psnr>
    <gender>male</gender>
    <grade>4</grade>
  </person>
</staffFile>
