=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex17.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3school.com.cn"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.w3school.com.cn"
elementFormDefault="qualified">
  <xs:element name="personen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="person" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="note_verbal">
    <xs:restriction base="xs:string">
      <xs:enumeration value="very good"/>
      <xs:enumeration value="good"/>
      <xs:enumeration value="satisfactory"/>
      <xs:enumeration value="sufficient"/>
      <xs:enumeration value="insufficient"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="gradeType">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="[1-6]{1}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="person">
    <xs:complexType>
      <xs:all>
        <xs:element name="firstName" type="xs:string"/>
        <xs:element name="familyName" type="xs:string"/>
        <xs:element ref="assessment" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="assessment">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="gradeType">
          <xs:attribute name="verbal" type="note_verbal" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex17a.xml
<?xml version="1.0" encoding="UTF-8"?>
<personen  xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex17.xsd">
  <person>
    <firstName>Andreas</firstName>
    <familyName>Leuter</familyName>
    <assessment verbal="good">2</assessment>
  </person>
  <person>
    <firstName>Reiner</firstName>
    <familyName>Luthard</familyName>
    <assessment verbal="insufficient">5</assessment>
  </person>
</personen>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_2/ex17a.xml
<?xml version="1.0" encoding="UTF-8"?>
<personen  xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex17.xsd">
  <person>
    <firstName>Andreas</firstName>
    <familyName>Leuter</familyName>
    <assessment verbal="good">2</assessment>
  </person>
  <person>
    <firstName>Reiner</firstName>
    <familyName>Luthard</familyName>
    <assessment verbal="insufficient">5</assessment>
  </person>
  <person>
    <firstName>Martin</firstName>
    <familyName>Immhoffer</familyName>
    <assessment verbal="insufficient">5</assessment>
  </person>
  <person>
    <firstName>Herbert</firstName>
    <familyName>Leisnig</familyName>
    <assessment verbal="insufficient">5</assessment>
  </person>
  <person>
    <firstName>Herbert</firstName>
    <familyName>Kunze</familyName>
    <assessment verbal="insufficient">4</assessment>
  </person>
  <person>
    <firstName>Anita</firstName>
    <familyName>Liebig</familyName>
    <assessment verbal="very good">1</assessment>
  </person>
</personen>
