=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex18.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns="http://www.w3school.com.cn"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.w3school.com.cn"
    elementFormDefault="qualified">

<!-- 根元素 -->
<xs:element name="zoo">
    <xs:complexType>
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="dwelling"/>
            <xs:element ref="zooanimal"/>
            <xs:element ref="zookeeper"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- ref1 -->
<xs:complexType name="dwellingtype">
    <xs:sequence>
        <xs:element name="id" type="xs:ID"/>
        <xs:element name="name" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<xs:element name="dwelling" type="dwellingtype"/>
<!-- ref1的子类1 -->
<xs:complexType name="building">
    <xs:complexContent>
        <xs:extension base="dwellingtype">
            <xs:choice>
                <xs:element name="area" type="xs:double"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
<!-- ref1的子类2 -->
<xs:complexType name="pond">
    <xs:complexContent>
        <xs:extension base="dwellingtype">
            <xs:choice>
                <xs:element name="depth" type="xs:double"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!-- ref2 -->
<xs:complexType name="zooanimaltype">
    <xs:sequence>
        <xs:element name="id" type="xs:ID"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="age" type="xs:positiveInteger"/>
    </xs:sequence>
    <xs:attribute name="zookeeper" type="xs:IDREF" use="required"/>
    <xs:attribute name="dwelling" type="xs:IDREF" use="required"/>
</xs:complexType>
<xs:element name="zooanimal" type="zooanimaltype"/>
<!-- ref2的子类1 -->
<xs:complexType name="mammal">
    <xs:complexContent>
        <xs:extension base="zooanimaltype">
            <xs:choice>
                <xs:element name="gestationperiod" type="xs:positiveInteger"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
<!-- 子类1的子类1 -->
<xs:complexType name="horse">
    <xs:complexContent>
        <xs:extension base="mammal">
            <xs:choice>
                <xs:element name="whitehorse" type="xs:boolean"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
<!-- 子类1的子类2 -->
<xs:complexType name="cat">
    <xs:complexContent>
        <xs:extension base="mammal">
            <xs:choice>
                <xs:element name="furcolor" type="xs:string"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!-- ref2的子类2 -->
<xs:complexType name="bird">
    <xs:complexContent>
        <xs:extension base="zooanimaltype">
            <xs:choice>
                <xs:element name="canfly" type="xs:boolean"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
<!-- 子类1的子类1 -->
<xs:complexType name="goose">
    <xs:complexContent>
        <xs:extension base="bird">
            <xs:choice>
                <xs:element name="slaughtweight" type="xs:positiveInteger"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
<!-- 子类1的子类1 -->
<xs:complexType name="starling">
    <xs:complexContent>
        <xs:extension base="bird">
            <xs:choice>
                <xs:element name="ringed" type="xs:boolean"/>
            </xs:choice>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!-- ref3 -->
<xs:complexType name="zookeepertype">
    <xs:sequence>
        <xs:element name="id" type="xs:ID"/>
        <xs:element name="name" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<xs:element name="zookeeper" type="zookeepertype"/>
</xs:schema>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex18.xml
<?xml version="1.0" encoding="UTF-8"?>
<zoo  xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex18.xsd">

    <dwelling xsi:type="building">
        <id>d001</id>
        <name>dwelling1</name>
        <area>1.1</area>
    </dwelling>
    <zooanimal dwelling='d001' zookeeper='zk001' xsi:type="horse">
        <id>a001</id>
        <name>animal1</name>
        <age>1</age>
        <gestationperiod>5</gestationperiod>
        <whitehorse>true</whitehorse>
    </zooanimal>
    <zookeeper>
        <id>zk001</id>
        <name>zookeeper1</name>
    </zookeeper>

    <dwelling xsi:type="pond">
        <id>d002</id>
        <name>dwelling2</name>
        <depth>1.2</depth>
    </dwelling>
    <zooanimal dwelling='d002' zookeeper="zk002" xsi:type="goose">
        <id>a002</id>
        <name>animal1</name>
        <age>1</age>
        <canfly>true</canfly>
        <slaughtweight>5</slaughtweight>
    </zooanimal>
    <zookeeper>
        <id>zk002</id>
        <name>zookeeper2</name>
    </zookeeper>
</zoo>
