=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/task9.dtd
<!ELEMENT library (shelfs, staff)>
<!ELEMENT shelfs (shelf+)>
<!ELEMENT staff (person+)>
<!ELEMENT shelf (book*)>
<!ELEMENT book (title, author, pages)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT person (name)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST library name CDATA #REQUIRED>
<!ATTLIST shelf 
    alphabetical (yes|no) #REQUIRED
    begin-at CDATA #IMPLIED
>
<!ATTLIST person staff-id CDATA #REQUIRED>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex09a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "task9.dtd">
<library name="National Library">
 <shelfs>
   <shelf alphabetical="no">
     <book>
       <title>About the importance of alphabetical ordering</title>
       <author>Helen I. Bartlett</author>
       <pages>431</pages>
     </book>
     <book>
       <title>The Book</title>
       <author>Yvette J. Coady</author>
       <pages>286</pages>
     </book>
   </shelf>
   <shelf alphabetical="yes" begin-at="A">
     <book>
       <title>All about Steam Locomotives</title>
       <author>Thomas C. Hill</author>
       <pages>161</pages>
     </book>
   </shelf>
   <shelf alphabetical="yes" begin-at="F">
     <book>
       <title>Garry's Grandious Cooking Recipes</title>
       <author>Garry J. Griggs</author>
       <pages>965</pages>
     </book>
     <book>
       <title>Kitchen Utilities: The Full Guide</title>
       <author>Maria F. Fluellen</author>
       <pages>216</pages>
     </book>
   </shelf>
   <shelf alphabetical="yes" begin-at="L">
   </shelf>
   <shelf alphabetical="yes" begin-at="R">
     <book>
       <title>Rise of Rome: a historical Timeline</title>
       <author>Alan G. Sheppard</author>
       <pages>753</pages>
     </book>
   </shelf>
   <shelf alphabetical="yes" begin-at="U">
     <book>
       <title>Xylphone Playing Made Easy</title>
       <author>Eleanor W. Hall</author>
       <pages>154</pages>
     </book>
   </shelf>
 </shelfs>
 <staff>
   <person staff-id="123">
     <name>Richard Doyle</name>
   </person>
   <person staff-id="124">
     <name>Dana Smart</name>
   </person>
   <person staff-id="125">
     <name>Terry Seawright</name>
   </person>
 </staff>
</library>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex09b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "task9.dtd">
<library name="Rockville Public Library">
 <shelfs>
   <shelf alphabetical="yes" begin-at="A">
     <book>
       <title>Dragons: Childish Fantasy of Shocking Reality?</title>
       <author>Kristen S. Newsome</author>
       <pages>407</pages>
     </book>
   </shelf>
   <shelf alphabetical="yes" begin-at="N">
     <book>
       <title>The One Book to Rule them all</title>
       <author>Josephine A. Gill</author>
       <pages>313</pages>
     </book>
   </shelf>
 </shelfs>
  <staff>
   <person staff-id="3">
     <name>Edgar Henderson</name>
   </person>
  </staff>
</library>
