=== ydzat/Workspace/XML/XML - Gaedke/ss14/task2.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns="urn:vsr:xml-pruefung:pflanzen" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="urn:vsr:xml-pruefung:pflanzen" 
elementFormDefault="qualified"> 

	<xs:element name="offers"> 
		<xs:complexType> 
			<xs:sequence maxOccurs="unbounded"> 
				<xs:element ref="product"/>
			</xs:sequence> 
		</xs:complexType>
	</xs:element> 

	<xs:complexType name="ct_planttype"> 
		<xs:sequence> 
			<xs:element name="harvest" type="xs:string"/> 
			<xs:element name="price" type="xs:double"/> 
			<xs:element name="supplier" type="xs:string"/>
		</xs:sequence> 
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType> 

	<xs:element name="product" type="ct_planttype"/> 
	<xs:complexType name="ct_fruit_planttype"> 
		<xs:complexContent> 
			<xs:extension base="ct_planttype"> 
				<xs:choice> 
					<xs:element name="stone" type="xs:boolean"/>
				</xs:choice> 
			</xs:extension> 
		</xs:complexContent>
	</xs:complexType> 

	<xs:complexType name="ct_vegtype"> 
		<xs:complexContent> 
			<xs:extension base="ct_planttype"> 
				<xs:choice> 
					<xs:element name="root" type="xs:boolean"/>
				</xs:choice> 
			</xs:extension> 
		</xs:complexContent> 
	</xs:complexType>
	
</xs:schema>

=== ydzat/Workspace/XML/XML - Gaedke/ss14/task2.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="task2.xsl"?>

<offers xmlns="urn:vsr:xml-pruefung:pflanzen" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:vsr:xml-pruefung:pflanzen task2.xsd"> 
	<product name="nuts"> 
		<harvest>Oct</harvest> 
		<price>2.10</price> 
		<supplier>Company1</supplier>
	</product> 
	<product name="apples" xsi:type="ct_fruit_planttype"> 
		<harvest>May</harvest> 
		<price>27.90</price> 
		<supplier>Company2</supplier> 
		<stone>true</stone>
	</product> 
	<product name="cabbage" xsi:type="ct_vegtype"> 
		<harvest>Sep</harvest> 
		<price>17.20</price> 
		<supplier>Company1</supplier> 
		<root>false</root>
	</product> 
</offers>
