=== ydzat/Workspace/XML/block1/ex14.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="urn:vsr:xml-werkzeuge:aufgabe2.9"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="urn:vsr:xml-werkzeuge:aufgabe2.9"
elementFormDefault="qualified">
  <xs:element name="vehicleList">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="vehicle"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="vehicletyp">
    <xs:sequence>
      <xs:element name="speed" type="xs:double"/>
      <xs:element name="price" type="xs:double"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="vehicle" type="vehicletyp"/>
  <xs:complexType name="watercraft">
    <xs:complexContent>
      <xs:extension base="vehicletyp">
        <xs:choice>
          <xs:element name="draft" type="xs:double"/>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="landVehicle">
    <xs:complexContent>
      <xs:extension base="vehicletyp">
        <xs:choice>
          <xs:element name="fordability" type="xs:double"/>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== ydzat/Workspace/XML/pru/XML/practice/learning_block_1/ex14b.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicleList xmlns="http://www.w3school.com.cn" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn ex14.xsd">
  <vehicle xsi:type="landVehicle" name="LKW">
    <speed>57.2</speed>
    <price>89483.10</price>
    <fordability>2.0</fordability>
  </vehicle>
  <vehicle  name="Schiff" xsi:type="watercraft" >
    <speed>22.0</speed>
    <price>728292.90</price>
    <draft>1.2</draft>
  </vehicle>
</vehicleList>
