<?xml version="1.0"?>
<!DOCTYPE sentence [
  <!ELEMENT sentence ((subject,predicate,object)+)>
  <!ELEMENT subject (#PCDATA)>
  <!ELEMENT predicate (#PCDATA)>
  <!ELEMENT object (#PCDATA)>
  <!ATTLIST subject plural (yes|no) "no">
  <!ENTITY vsr "Professur
  Verteilte und selbsorganisierende
  Rechnersysteme">
  <!ENTITY nbsp "&amp;#160;" >
]>
<sentence>
  <subject>The &amp;vsr;&amp;nbsp;</subject>
  <predicate>conducts</predicate>
  <object>research &amp; education.</object>
  <subject plural="yes">Universities</subject>
  <predicate><![CDATA[ have <= ]]></predicate>
  <object>a &amp;vsr;.</object>
</sentence>