<?xml version="1.0"?>
<!DOCTYPE storage [
  <!ELEMENT storage (house*, responsiblee)>
  <!ELEMENT house      (shelve*)>
  <!ELEMENT shelve (item+)>
  <!ELEMENT item    (description, number, remark?)>
  <!ELEMENT description    (#PCDATA)>
  <!ELEMENT number    (#PCDATA)>
  <!ELEMENT remark    (#PCDATA)>
  <!ELEMENT responsiblee  (responsible+)>
  <!ELEMENT responsible  (surname)>
  <!ELEMENT surname  (#PCDATA)>
  <!ATTLIST house id ID #REQUIRED>
  <!ATTLIST shelve id CDATA #REQUIRED>
  <!ATTLIST responsible for IDREFS #REQUIRED>
]>
<storage>
   <responsiblee>
      <responsible for="rear front">
      <surname>Krause</surname>
      </responsible>
      <responsible for="middle">
      <surname>Krause</surname>
      </responsible>
   </responsiblee>
</storage>