<?xml version="1.0"?>
<!DOCTYPE storage [
  <!ELEMENT storage (house*, responsiblee)>
  <!ELEMENT house      (shelve*)>
  <!ELEMENT shelve (item+)>
  <!ELEMENT item    (description, number, remark?)>
  <!ELEMENT description    (#PCDATA)>
  <!ELEMENT number    (#PCDATA)>
  <!ELEMENT remark    (#PCDATA)>
  <!ELEMENT responsiblee  (responsible+)>
  <!ELEMENT responsible  (surname)>
  <!ELEMENT surname  (#PCDATA)>
  <!ATTLIST house id ID #REQUIRED>
  <!ATTLIST shelve id CDATA #REQUIRED>
  <!ATTLIST responsible for IDREFS #REQUIRED>
]>
<storage>
   <house id="front">
    <shelve id="reg1">
     <item>
      <description>hammer</description>
      <number>1234</number>
      <remark>mighty</remark>
   </item>
     <item>
      <description>pliers</description>
      <number>6737</number>
   </item>
    </shelve>
    <shelve id="reg2">
     <item>
      <description>sockel</description>
      <number>6573</number>
      <remark>worn</remark>
   </item>
     <item>
      <description>oese</description>
      <number>8393</number>
   </item>
    </shelve>
   </house>
   <house id="middle">
    <shelve id="reg5">
     <item>
      <description>knive</description>
      <number>7282</number>
      <remark>rusty</remark>
   </item>
     <item>
      <description>peg</description>
      <number>8944</number>
   </item>
    </shelve>
   </house>
   <house id="rear">
    <shelve id="reg4">
     <item>
      <description>key</description>
      <number>52365</number>
   </item>
     <item>
      <description>safe</description>
      <number>6734</number>
   </item>
    </shelve>
   </house>
   <responsiblee>
      <responsible for="rear front">
      <surname>Krause</surname>
      </responsible>
      <responsible for="middle">
      <surname>Krause</surname>
      </responsible>
   </responsiblee>
</storage>